### PR TITLE
Friendly error message if logging directory does not exist

### PR DESCRIPTION
**Pull request by ebadkamil**
This PR may address the issue https://github.com/ess-dmsc/forwarder/issues/6

@mattclarke

### CODE REVIEW

**Comment by mattclarke** [comment]
I think I would prefer it to exit with a warning rather than create a directory in an arbitrary location.
It may be that somebody has just mistyped the logging path for example.

**Comment by ebadkamil** [comment]
Good point. Now it only looks for folder name existence and exit with a message in case the folder does not exist.

**Review by matthew-d-jones — COMMENTED** [review]
Manually tested and it displays message as expected :+1: 

@mattclarke any opinion on whether it should create the logger anyway (without the file sink) and display the message as an error log? That would ensure it reaches graylog if configured to send logs there.

**Comment by mattclarke** [comment]
@matthew-d-jones Yes, I think that is a good idea

**Comment by matthew-d-jones** [comment]
@ebadkamil To clarify:
I mean create the logger with the console and, potentially, graylog sinks and display the message with `logger.error` instead of `print`.
The main advantage would be in case someone is remote deploying the Forwarder and expects any errors to be reported to the graylog server.

**Review by matthew-d-jones — APPROVED** [review]
Thanks, looks good to me.

**Comment by ebadkamil** [comment]
Thanks @matthew-d-jones and @mattclarke

**Pull request merged**
